version: '3.9'
name: spring-boot-keycloak-from-scratch

services:
  cusomer-api-db:
    container_name: customer-api-db
    hostname: customer-api-db
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_CUSTOMER_API_DB_DATABASE}
      MYSQL_USER: ${MYSQL_CUSTOMER_API_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_CUSTOMER_API_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - customer-api-db:/var/lib/mysql
      - customer-api-db:/docker-entrypoint-initdb.d
    networks:
      - spring-boot-keycloak-from-scratch
volumes:
  keycloak-db-volume:
    driver: local
  customer-api-db:
    driver: local
networks:
  spring-boot-keycloak-from-scratch:
    driver: bridge

